---
title: ExperimentAI Stage 2 - Make a Classification Application
hero_image: images/banner.jpg
description: design-project-template description
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Create a machine learning model
- title: Add values to the model
- title: Make a Scratch application
- title: Pick a genre to search
- title: Collect song data
- title: Keep on searching
- title: Design your interface
- title: Send data to your ML model
- title: What next?
