---
title: ExperimentAI Stage 2 - Make a Scratch Application
hero_image: images/banner.png
description: design-project-template description
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Create your machine learning model
- title: Add values to your model
- title: Make a Scratch application
- title: Pick a genre to search
- title: Upgrade your project
- title: Share
- title: What next?
