---
title: ExperimentAI Stage 2 - Make a Scratch Application
hero_image: images/banner.png
description: design-project-template description
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Create your machine learning model
- title: Add values to your model
- title: Make a Scratch application
- title: Pick a genre to search
- title: Collect song data
- title: Keep on searching
- title: Classify song data
- title: Link to your ML model
- title: Design your interface
- title: What next?
